### PR TITLE
Add gui.

### PR DESCRIPTION
**Pull request by LyfeOnEdge**
This is a resizable cross-platform compatible gui for custom-install.py
Requires tkinter.
Runs the script on a separate thread and captures the output to prevent blocking.

### CODE REVIEW

**Comment by ihaveamac** [comment]
This is awkward... Because there already was one on module-rewrite. Unlike this PR, it was implemented directly into the module rather than being a command line wrapper. I guess it wasn’t obvious though since I haven’t worked on this project for a while though. I’ll try it out soon.

**Comment by LyfeOnEdge** [comment]
The gui running in this manner means the install code and the gui code are independent so you can update the script without affecting the gui. I was aware of the other one but kinda unsatisfied with it. I'd be happy to spruce that one up and make it a little bit more consistent across platforms, but I felt this was a much cleaner way of doing things.

**Comment by LyfeOnEdge** [comment]
I also added a theming system, users can now customize the gui using style.py, more customization options will be coming soon.

**Comment by LyfeOnEdge** [comment]
@ihaveamac I have tested the app with the updated gui script, it should still work fine.

**Comment by ihaveamac** [comment]
Could this be committed to module-rewrite instead? I don't want to touch master much right now.

**Comment by ihaveamac** [comment]
Actually scratch that. I will split it off to another branch.

**Comment by ihaveamac** [comment]
Merged into module-new-gui. 5c41f03784ee5c3ee2c8ac124ce0a654ecb1872a Thanks!

**Pull request closed without merging**
